# Generated by Django 4.2.10 on 2025-11-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountuser',
            table=None,
        ),
    ]
